apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: regiinaldo/back-gurudoamor:main-${{github.sha}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.stage.svc.cluster.local:5432/gurudoamor
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: LOG_LEVEL
            - name: TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: TIMEZONE
