apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: production
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=         # base64 de 'postgres'
  POSTGRES_PASSWORD: cG9zdG3nZQ==     # base64 de 'postgre'
  POSTGRES_DB: Z3VydWRvYW1vcg==       # base64 de 'gurudoamor'
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMuc3RhZ2Uuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9ndXJ1ZG9hbW9yCg==

