apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: regiinaldo/front-gurudoamor:main-${{github.sha}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.stage.svc.cluster.local:5432/gurudoamor
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD