apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: regiinaldo/back-gurudoamor:dev-${{github.sha}}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.stage.svc.cluster.local:5432/gurudoamor
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD