name: CI/CD para Kubernetes (Stage)

on:
  push:
    branches:
      - dev

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #- name: Rodar testes com Maven
      #  run: mvn clean test -X -f back/pom.xml

      - name: Build da imagem Docker
        run: |
          docker build -t us-central1-docker.pkg.dev/desafio-pipeline/desafio-pipeline/backend:dev-${{ github.sha }} ./back

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Login no Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Push da imagem para o Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/desafio-pipeline/desafio-pipeline/backend:dev-${{ github.sha }}

      - name: Instalar gcloud + kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: desafio-pipeline
          install_components: 'kubectl'
          export_default_credentials: true

      - name: Acessar cluster do GKE
        run: |
          gcloud container clusters get-credentials desafio-pipeline-01 \
            --zone us-central1 \
            --project desafio-pipeline

      - name: Aplicar manifests no namespace stage
        run: |
          kubectl apply -f k8s/base/ --namespace=stage

      - name: Atualizar imagem do deployment
        run: |
          kubectl set image deployment/backend backend=us-central1-docker.pkg.dev/desafio-pipeline/desafio-pipeline/backend:dev-${{ github.sha }} -n stage
