name: CI/CD para Frontend Angular (Production)

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: front-agora

      - name: Build do Angular
        run: npm run build -- --configuration production
        working-directory: front-agora

      - name: Build da imagem Docker
        run: |
          docker build -t regiinaldo/front-gurudoamor:production-${{ github.sha }} .
        working-directory: front-agora

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push da imagem para o Docker Hub
        run: |
          docker push regiinaldo/front-gurudoamor:production-${{ github.sha }}

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Instalar gcloud + kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: desafio-pipeline
          install_components: 'kubectl'
          export_default_credentials: true

      - name: Acessar cluster do GKE e fazer deploy
        run: |
          gcloud container clusters get-credentials cluster-desafio-pipeline \
            --zone us-central1-a \
            --project desafio-pipeline

          kubectl apply -f k8s/base/ --namespace=production
          kubectl set image deployment/frontend frontend=regiinaldo/front-gurudoamor:production-${{ github.sha }} -n production
  